Checklist Analytic Receiver
CenterforYouthEngagement/AppBookDataAnalyzer pull request #36
Opened 2022-03-30 22:06 UTC by sdub18

Should cover the checklist analytic. Please let me know if I missed anything by mistake!

2022-04-01 01:58 UTC, jeremy6462 requested changes
Thanks for adding this in! While the query is correct, I have some nitpicks for clarity. All good after that!

2022-04-01 01:58 UTC, jeremy6462 commented on AppBookDataAnalyzer/Analytics for Rows/ChecklistNumItemsTapped.swift
> +                    ON \(Database.ChecklistItems.Column.id) = \(Database.ChecklistSelectedItems.Column.checklistItemId)
For clarity, this should be `ON \(Database.ChecklistItems.tableName).\(Database.ChecklistItems.Column.id) = \(Database.ChecklistSelectedItems.tableName).\(Database.ChecklistSelectedItems.Column.checklistItemId)`. This means that we'll join on `checklist_items.id = checklist_selected_items.checklist_item_id` which is more specific than what is written now: `id = checklist_item_id`.

2022-04-01 01:58 UTC, jeremy6462 commented on AppBookDataAnalyzer/Analytics for Rows/ChecklistNumItemsTapped.swift
> +                    ON \(Database.QuestionPageJoin.Column.id) = \(Database.QuestionPageJoin.Column.questionId)
Similarly to above, we should include the table names here for clarity. Moreover, we shouldn't join on two columns of the same table (you're joining on `question_to_page_join.id = question_to_page_join.question_id` here, when really it should be `question_to_page_join.id = checklist_items.question_id`

2022-04-01 01:58 UTC, jeremy6462 commented on AppBookDataAnalyzer/Analytics for Rows/ChecklistNumItemsTapped.swift
> +                    ON \(Database.QuestionPageJoin.Column.id) = \(Database.QuestionPageJoin.Column.questionId)
Similarly to above, we should include the table names here for clarity. Moreover, we shouldn't join on two columns of the same table (you're joining on `question_to_page_join.id = question_to_page_join.question_id` here, when really it should be `question_to_page_join.id = checklist_items.question_id`

2022-04-08 22:45 UTC, fjfur10 approved these changes
Looks good to me, you may want to remove the `.xcuserstate` before merging though (the file should be added to `.gitignore` in `main`)

2022-04-08 23:07 UTC, jeremy6462 commented
> Looks good to me, you may want to remove the `.xcuserstate` before merging though (the file should be added to `.gitignore` in `main`)

I think if you merge main into this branch that should remove the file

2022-04-12 16:47 UTC, sdub18 commented
@jeremy6462 Could you give this PR another run through? I believe I fixed the issues with the SQL query

2022-04-12 16:47 UTC, jeremy6462 approved these changes
All good from my end now!

2022-04-12 16:50 UTC, merged